# Chapter 5: 간단한 메소드 선언

이 단원에서는 main 메소드 이외의 Java 메소드를 정의하는 방법을 배웁니다. 이 과정에서 argument, parameter 및 return value로 작업하는 방법을 알게됩니다.

## 99

많은 영화의 등급을 계산하려면 **movirRating**과 같은 이름의 등급 계산 메소드를 정의해야 합니다. **movieRating** 메서드를 정의하면 다음 예와 같이 main 메서드에서 **movieRating** 메서드를 호출 할 수 있습니다.

[source, java]
--
public class Demonstrate {
  // Definition of movieRating goes here
  public static void main (String [] args) {
    System.out.print("The rating of the movie is ");
    System.out.println(movieRating(6, 9, 8));
  }
}
--

예에서 movieRating 메서드에는 6, 9 및 8과 같은 세 개의 인수가 있습니다. Java는 메서드 인수를 쉼표로 구분해야하는 것을 요구합니다.

## 100

**movieRating** 메서드를 호출 할 때마다 Java 컴파일러는 다음을 수행해야합니다.

* 사용할 movieRating 메서드를 결정합니다.
* 인수 표현식을 평가합니다.
* 매개변수 - 즉 s, a 및 d와 같은 매개변수에 인수 표현식 값을 할당합니다.
* 식 s + a + d을 계산합니다.
* 다른 계산에 사용하기 위해 s + a + d의 값을 반환합니다.

## 100

**movieRating** 메서드를 호출 할 때마다 Java 컴파일러는 다음을 수행해야합니다.

* 사용할 movieRating 메서드를 결정합니다.
* 인수 표현식을 평가합니다.
* 매개변수 - 즉 s, a 및 d와 같은 매개변수에 인수 표현식 값을 할당합니다.
* 식 s + a + d을 계산합니다.
* 다른 계산에 사용하기 위해 s + a + d의 값을 반환합니다.

## 101

**movieRating** 메소드를 다음과 같이 정의합니다.

[source, java]
----
public class Demonstrate {
  public static int movieRating (int s, int a, int d) {
    return s + a + d;
  }
  // Definition of main goes here
}
----
## 102

각 부분에 대한 설명은 다음과 같습니다.

[source, java]
----
*-- 메서드를 다른 메서드에서 호출할 수 있음을 나타냅니다
|       *-- 메소드가 클래스 메소드임을 나타냅니다
|       |      *--Java에 반환된 값의 데이터 유형을 알려줍니다
|       |      |     *-- 메서드의 이름을 Java에 알려줍니다
|       |      |     |           *-- 매개 변수의 이름과 데이터 유형을 Java에 알려줍니다
|       |      |     |           |
v       v      v     v           v
------ ------ --- ------------ -------------------
public static int movieRating (int s, int a, int d) {   <--*
  return s + a + d;                                        |
  ------ ---------         	        바디가 시작되는 곳의 표시 ---*
    ^       ^
    |       |
    |       *-- 값을 반환할 식
    *-- 메서드에서 반환할 값을 표시합니다

} <-- 바디가 끝나는 곳의 표시
----

== 103

메소드의 Parameter는 호출될 때 마다 argument 값으로 초기화되는 변수일 뿐입니다. 다른 변수와 마찬가지로 parameter에 새 값을 할당할 수 있지만, 많은 프로그래머는 이런 할당을 나쁜 프로그래밍 관행으로 간주합니다.

== 104

Java 메서드를 정의 할 때 parameter 및 return value의 data type을 지정해야합니다.

각 메서드의 각 parameter의 data type은 parameter를 도입하는 위치에서 지정합니다.
메서드에서 return되는 값은 메서드 이름을 지정하는 위치에서 data type을 지정합니다.

== 105

마지막으로 키워드를 사용하여 정의하는 메서드의 종류를 지정합니다.

**static** 키워드는 **movieRating** 메서드가 클래스 메서드임을 나타냅니다. **static** 키워드를 생략하면 Chapter 10에서 설명된 대로 인스턴스 메서드가 정의됩니다.
**public** 키워드는 모든 클래스에서 **movieRating** 메서드를 호출 할 수 있음을 나타냅니다. **protected** 또는 **private** 키워드를 사용하면 **movieRating** 메서드에 대한 액세스가 제한되어 있음을 나타냅니다.

== 106

다음 예에서 movieRating 메서드의 정의는 프로그램에서 하드 코딩된 테스트 데이터를 포함합니다. 이 프로그램은 실행될 때 결과 값이 23이됩니다.

[source, java]
----
public class Demonstrate {
  public static void main (String [] args) {
    int script = 6;
    int acting = 9;
    int direction = 8;

    System.out.print("The rating of the movie is ");
    System.out.println(movieRating(script, acting, direction));
  }
  public static int movieRating (int s, int a, int d) {
      return s + a + d;
  }
}
--- Result ---
The rating of the movie is 23
----

