= Chapter 10: 클래스 메소드 선언

이 단원에서는 클래스 인스턴스 argument가 일반적인 argument 메커니즘을 통해 제공되는 대신 필드 선택 연산자(.)를 통해 호출되는 방식으로 정의할 수 있는 메소드를 만드는 방법을 학습합니다.

== 192

항목 178의 프로그램에서 **Movie** 인스턴스에 대해 다음과 같이 **rating** 메소드가 정의된 것을 볼 수 있습니다.

[source, java]
----
public static int rating (Movie m) {
	return m.script + m.acting + m.direction;
}
----

**rating**을 **인스턴스 메소드**로 바꿀 수 있습니다. 각 인스턴스 메소드에는 하나의 특수 argument인 **대상(target)**이 있습니다.

* 특수 argument의 값은 클래스 인스턴스입니다. 클래스 인스턴스의 정의에는 인스턴스 메소드의 정의가 포함됩니다.
* 특수 argument는 괄호 안에 다른 일반 argument와 함께 나타나지 않습니다. 대신, 특수 argument는 인스턴스 변수 참조와 유사한 방식으로 필드 선택 연산자를 통해 인스턴스 메소드 이름과 결합됩니다.

== 193

예를 들어, **Movie** 클래스에 대해 194 항목에서 정의될 **rating** 인스턴스 메소드가 변수 **m**으로 지정된 **Movie** 인스턴스에서 작동하도록 하려면 다음과 같이 작성합니다.

[source, java]
----
m.rating
----

이 항목에서 정의된 rating 인스턴스 메소드는 argument가 없는 것입니다.

== 194

인스턴스 메소드에서 인스턴스 변수에 대한 모든 참조는 대상 인스턴스에서 속하는 특정 인스턴스 변수를 참조합니다. 따라서 **rating**을 다음과 같이 인스턴스 메소드로 정의할 수 있습니다.

[source, java]
----
public class Movie {
  public int script;
  public int acting;
  public int direction;

  public int rating () {
	  return script + acting + direction;
  }
}
----

이 **rating** 인스턴스 메소드가 특정 **Movie** 대상에서 호출 될 때, **rating**의 정의에 나타나는 **script**, **acting**, **direction** 변수는 자동으로 해당 대상과 관련된 **script**, **acting**, **direction** 인스턴스 변수를 참조합니다.

[source, java]
----
public class Demonstrate {
  public static void main (String argv[]) {
    Movie m = new Movie();
    m.script = 8;
    m.acting = 9;
    m.direction = 6;
    System.out.println("The rating of the movie is " + m.rating());
  }
}
----

[source]
----
--- 결과 ---
The rating of the movie is 23
----

== 195

**rating** 인스턴스 메소드와 **rating** 클래스 메소드의 정의 사이의 차이점에 유의하십시오.

[source, java]
----
      *--  인스턴스 메서드에 static 키워드 없음
      |            *-- 인스턴스 메서드는
      |            |   인스턴스 인수가 필요 없음
      v            v
public int rating ( ) {
 return script + acting + direction;
}      ^       ^        ^
       *-------*--------*-- 인스턴스 메서드는 인스턴스를
                            대상으로하는 인스턴스 변수를 가정합니다.

         *-- 클래스 메서드에는 static 키워드가 나타납니다.
         |                  *-- 클래스 메서드는
         |                  |   인스턴스 인수가 필요합니다.
         v                  v
       ------             -------
public static int rating (Movie m) {
 return m.script + m.acting + m.direction;
}       ^          ^          ^
        *----------*----------*-- 클래스 메서드는
                                  필드 선택 연산자를 사용하여
                                  인스턴스 변수를 참조해야합니다.
----

== 196

또한 인스턴스 메서드와 클래스 메서드가 호출되는 방식의 차이점에 유의하십시오.

[source, java]
----
* - 인스턴스 메서드에는 인스턴스 대상이 있습니다.
|        * - 인스턴스 인수가 필요하지 않습니다.
|        |
v        v
m.rating( )
* - 클래스 메서드에는 클래스 이름이 대상 위치에 있습니다.
|            * - 인스턴스 인수가 필요합니다.
|            |
v            v
Movie.rating(m)
----

== 197

이제 **Movie** 클래스의 194 항목에서 인스턴스 메서드로 정의된 rating의 한 버전과 Symphony 클래스의 인스턴스 메서드로 정의된 다른 버전으로 프로그램을 작성할 수 있습니다.

[source, java]
----
public class Symphony {
  public int music;
  public int playing;
  public int conducting;

  public int rating () {
  	return music + playing + conducting;
  }
}
----

Java는 대상 인스턴스의 클래스에서 정의된 메서드를 선택합니다. 다음 예제와 같습니다.

[source, java]
----
public class Demonstrate {
  public static void main(String argv[]) {
    Movie m = new Movie();
    m.script = 8;
    m.acting = 9;
    m.direction = 6;
    Symphony s = new Symphony();
    s.music = 7;
    s.playing = 8;
    s.conducting = 5;
    System.out.println("The rating of the movie is " + m.rating());
    System.out.println("The rating of the symphony is " + s.rating());
  }
}
----

[source]
----
--- 결과 ---
The rating of the movie is 23
The rating of the symphony is 20
----

== 198

인스턴스 메소드가 호출 될 때 대상 인수 값은 특수 parameter this에 할당됩니다. 따라서 this의 parameter값은 대상 클래스 인스턴스입니다. **Movie rating** 인스턴스 메소드를 두 가지 방법으로 작성할 수 있습니다. 194 항목에서 소개 된 방식은 인스턴스 변수가 대상 인스턴스를 참조하는 관례를 이용합니다.

[source, java]
----
public class Movie {
  public int music;
  public int playing;
  public int conducting;

  public int rating () {
  	return script + acting + direction;
  }
}
----

**this** parameter를 사용하여 대상 인스턴스를 명시 적으로 참조하는 방법으로 **rating**을 정의하는 다른 방법도 있습니다.

[source, java]
----
public class Movie {
  public int music;
  public int playing;
  public int conducting;

	public int rating () {
		return this.script + this.acting + this.direction;
	}
}
----

일부 프로그래머는 프로그램을 이해하기 쉽게 만드는 데 **this**를 자주 사용하며, 이 강의에서는 반드시 필요한 경우에만 **this**를 사용합니다.

== 199

**this** parameter의 값은 인스턴스 주소의 복사본입니다. 인스턴스 자체의 복사본이 아닙니다. 따라서 인스턴스 메소드 내에서 인스턴스 변수를 재할당하면 대상 인스턴스의 인스턴수 변수의 값이 변경됩니다.

따라서, **m**의 값이 movie이고 **m**을 대상으로 인스턴스 메소드를 호출하고 인스턴스 메소드가 인스턴스 변수의 값을 변경하면 **m**에 할당된 movie에서 인스턴스 변수가 변경됨을 볼 수 있습니다.

== 200

인스턴스 메소드는 대상 인스턴스 외에도 일반적인 인자를 가질 수 있습니다. 예를 들어, 대상 인스턴스의 평점에 일반적인 인자로 제공된 스케일 요소를 곱하는 scaledRating 인스턴스 메소드를 가질 수 있습니다.

[source, java]
----
*-- 대상 인스턴스
|
|               *-- 일반적인 인자
|               |
v               v
m.scaledRating(0.75)
----

scaledRating 인스턴스 메소드의 정의는 rating 인스턴스 메소드와 유사합니다. 유일한 차이점은 일반 매개 변수 scaleFactor의 추가입니다.

[source, java]
----
public class Movie {
  // 우선, 인스턴스 변수를 정의합니다:
  public int music;
  public int playing;
  public int conducting;

  // 평점 정의:
  public int rating (double scaleFactor) {
  	return (int) (scaleFactor * (script + acting + direction));
  }
}
----

다음은 새 버전의 작동 방식을 보여줍니다.

[source, java]
----
public class Demonstrate {
  // main 정의:
  public static void main (String [] args) {
    Movie m = new Movie();
    m.script = 8;
    m.acting = 9;
    m.direction = 6;
    System.out.println("The rating of the movie is " + m.rating(0.75));
  }
}
----

[source]
----
--- 결과 ---
The rating of the movie is 17
----

== 201

인스턴스 메소드의 도입으로 클래스 정의에 나타날 수 있는 네 가지 요소를 볼 수 있습니다.

[source]
----
A class definition
*--------------------*
|                    |
| Class methods      |
|                    |
|                    |
| Class variables    |
|                    |
|                    |
| Instance variables |
|                    |
|                    |
| Instance methods   |
|                    |
*--------------------*
----

== 202: 연습 문제

189 항목에서 **BoxCar** 인스턴스의 **volume** 메소드를 인스턴스 메소드로 바꾸세요.

== 203: Summerize

* public 클래스에서 public instance method를 정의하려면, 다음 패턴을 사용하세요.

[source, java]
----
public class class name {
  public return type method name
    (data type 1 parameter 1,
     ...,
     data type l parameter l) {
    declaration 1
    ...
    declaration m
    statement 1
    ...
    statement n
  }
}
----

* 인스턴스 메소드를 호출하려면, **대상 인스턴스**와 **메소드 이름**을 필드 선택 연산자로 결합하여 지정하세요.

[source, java]
----
target instance.method name(ordinary arguments)
----

* 명시적으로 대상을 참조하려면, **this** parameter를 사용하세요.