= Chapter 12: Getter와 Setter 메소드 선언

이 단원에서는 getter 및 setter 인스턴스 메소드가 선언된 변수 값을 처리하는데 도움이 된다는 것을 배웁니다.

== 222
필드 선택 연산자를 사용하여 인스턴스 변수 값을 직접 참조할 수 있다는 것을 배웠습니다. 예를 들어, Attraction 클래스를 정의하고 **minutes** 인스턴스 변수를 정의하여 놀이기구의 지속 시간을 분 단위로 기록할 수 있습니다. 특정 Attraction x에서 해당 인스턴스 변수 값을 참조할 수 있습니다.

[source, java]
----
x.minute
----

또는 인스턴스 변수 값을 반환하는 인스턴스 메소드를 정의하여 간접적으로 인스턴스 변수 값을 참조할 수 있습니다. 예를 들어 Attraction 클래스 정의에서 **getMinites** 인스턴스 메소드는 **minutes** 인스턴스 변수의 값을 반환합니다.

[source, java]
----
public class Attraction {
    // First, define instance variable:
    public int minutes;
    // Define zero-parameter constructor:
    public Attraction () {minutes = 75;}
    // Define one-parameter constructor:
    public Attraction (int m) {minutes = m;}
    // Define getter:
    public int getMinutes () {
        return minutes;
    }
}
----

**getMinites**가 정의되면 특정 Attraction x의 **minites** 인스턴스 변수 갑을 참조하는 또 다른 방법을 가지게 됩니다.

[source, java]
----
x.getMinutes()
----

== 223

**Getter**는 인스턴스에서 정보를 추출하는 메소드입니다.

인스턴스 변수에 직접 액세스하는 대신 getter를 사용하는 이유 중 하나는 getter에 추가 계산을 포함할 수 있다는 것입니다. 예를 들어, 프로그램이 **minutes** 인스턴스 변수에 얼마나 자주 액세스 하는지 걱정된다면 각 액세스를 알리는 문을 **getMinites** getter에 추가할 수 있습니다.

[source, java]
----
public class Attraction {
    public int minutes;
    public Attraction () {minutes = 75;}
    public Attraction (int m) {minutes = m;}
    // Define getter:
    public int getMinutes () {
      	System.out.println("Accessing a value ...");
        return minutes;
    }
}
----

== 224

마찬가지로, 인스턴스 변수 값에 직접 할당할 필요가 없습니다. 대신, 실제 값을 할당하는 인스턴스 메소드를 정의하여 간접적으로 인스턴스 변수 값이 할당할 수 있습니다.

일반적으로 **setter**는 인스턴스에 정보를 삽입하는 메소드입니다. setter는 mutator라고 부르기도 합니다.

다음 **Atttraction** 클래스 정의에서는 **setMinites**가 **minutes** 인스턴스 변수에 값을 할당합니다.

[source, java]
----
public class Attraction {
    public int minutes;
    public Attraction () {minutes = 75;}
    public Attraction (int m) {minutes = m;}
    // Define getter:
    public int getMinutes () {
  	    return minutes;
    }
    // Define setter:
    public void setMinutes (int m) {
  	    minutes = m;
    }
}
----

**setMinites**가 정의되면, 특정 Attraction x의 **minutes** 인스턴스 변수값에 값을 할당하는 다른 방법을 가지게 됩니다.

[source, java]
----
x.setMinutes(4)
----

== 225

224 항목에 정의된 대로 **setMinites**의 유일한 목적은 인스턴스 변수에 값을 할당하는 것이므로, **void**로 표시되어 있어 반환할 값이 없음을 나타냅니다. 원하는 경우, 이전 값 또는 새 값이 반환되도록 **setMinites**를 작성할 수 있습니다.

== 226

인스턴스 변수에 값을 직접 할당하는 대신 setter를 사용하는 이유 중 하나는 setter에 추가 계산을 포함할 수 있다는 것입니다. 항목 223에서는 **getMinutes** getter에 각 액세스를 알리는 문을 추가하는 방법을 보여주었습니다. 다음은 **setMinites** setter에 동일한 향상 기능을 제공합니다.

[source, java]
----
public class Attraction {
    public int minutes;
    public Attraction () {minutes = 75;}
    public Attraction (int m) {minutes = m;}
    // Define getter:
    public int getMinutes () {
  	    return minutes;
    }
    // Define setter:
    public void setMinutes (int m) {
  	    System.out.println("Assigning a value ...");
    minutes = m;
    }
}
----

== 227

표시 출력 변경과 인스턴스 변수 변경을 조정해야 하는 경우 setter를 사용하는 것이 특히 유용합니다. 이러한 조정에 대해 Chapter 41에서 학습합니다.

== 228

가상 인스턴스 변수에 액세스하기 위한 getter 및 setter를 사용할 수도 있습니다. 이러한 가상 인스턴스 변수는 실제로 존재하지 않지만, 존재하는 인스턴스 변수에서 계산된 값을 사용하여 값을 계산할 수 있습니다. 예를 들어, **getHours** 및 **setHours**를 만들 수 있으며, **double** 유형의 가상 **hours** 인스턴스 변수의 내용처럼 보이지만 사실은 **minutes** 인스턴스 변수의 값을 사용합니다.

[source, java]
----
public class Attraction {
    public int minutes;
    public Attraction () {minutes = 75;}
    public Attraction (int m) {minutes = m;}
    // Define getters:
    public int getMinutes () {return minutes;}
    public double getHours () {
      	return minutes / 60.0;
    }
    // Define setters:
    public void setMinutes (int m) {minutes = m;}
    public void setHours (double h) {
  	    minutes = (int)(h * 60);
    }
}
----

**getMinites**, **setMinutes**, **getHours**, **setHours** 메소드의 이름은 **get** 및 **set** 접두사가 붙으므로 메소드가 getter 및 setter가 분명합니다. 그러나, **get**및 **set** 사용은 강제되는 것이 아니라 관례입니다. 그러나, 일부 Java 프로그래밍 환경에서 getter및 setter가 **get** 및 **set**으로 시작하는 이름을 가지는 것으로 생각되기 때문에 관례에 따르는 것이 좋습니다.

== 229

생성자 메소드는 Java 언어의 일부이지만 getter 및 setter 메소드는 그렇지 않습니다. 그러나, 이 장에서 설명한대로 getter 및 setter 메소드의 사용은 사용하는 프로그래밍 언어와 관계없이 많은 프로그래머들이 권장합니다. 이유는 Chapter 13에서 학습합니다.

== 230

188 항목에서 작성한 **BoxCar** 클래스에 대한 getter 및 setter를 작성하세요.

== 231: Summary

* getter 및 setter 인스턴스 메소드는 인스턴스 변수 액세스 및 할당에 대한 간접적인 경로를 제공합니다.
* 가상 인스턴스 변수로 getter 및 setter 인스턴스 메소드를 정의할 수 있습니다.
* 인스턴수 변수 값을 getter를 사용하여 참조하려면, 아래와 같이 작성합니다.

[source, java]
----
instance.getter_method()
----

* 인스턴스 변수 값을 setter를 사용하여 할당하려면, 아래와 같이 작성합니다.

[source, java]
----
instance.setter_method(new-value expression)
----