= Chapter 7: Procedure Abstraction

이 단원에서는 *procedure abstraction* 개념에 대해 배우며, 이를 통해 효율성을 높이고 프로그램을 유지 관리하기 쉽게 만듭니다.

=== 139

연산의 세부 정보를 메소드 안으로 이동할 때 *procedure abstraction*을 수행한다 라고 하고, 연산이 수행되는 방법의 세부 정보를 *procedure abstraction barrier* 뒤에 숨긴다라고 말합니다.

**Procedure abstraction**의 주요 장점은 _프로그램의 재사용이 쉬워진다_ 라고 말합니다.

== 140

**Procedure abstraction**의 두 번째 장점은 _세부 정보를 가려서 프로그램을 이해하기 쉽게 만들고 고수준 단계에 집중할 수 있게 하는 것_ 입니다.

== 141

**Procedure abstraction**의 세 번째 장점은 _프로그램을 쉽게 디버깅_ 할 수 있다는 것입니다. 프로그램을 작고 독립적인 디버깅 가능한 조각으로 나누어 강력한 *분할 정복(divide and conquer) 문제 해결로 활용합니다.

== 142

**Procedure abstraction**의 네 번째 장점은 _반복 계산을 쉽게 추가할 수 있다는 것_ 입니다. 예를 들어, Segment 114에서 ekdmarhk rkxdl *movieRating* 메소드가 정의되어 있는 것을 볼 수 있습니다.

[source, java]
----
public class Movie {
  // Define movieRating:
  public static int movieRating (int s, int a, int d) {
	  return s + a + d;
  }
}
----

계산할 때마다 등급을 표시하는 라인을 쉽게 추가핳 수 있습니다.

[source, java]
----
public class Movie {
  // Define movieRating:
  public static int movieRating (int s, int a, int d) {
    System.out.print("The rating of the movie is " + (s + a + d));
    return s + a + d;
  }
}
----

따라서 등급이 계산되는 모든 위치를 찾을 필요가 없으므로 *movieRating* 메소드의 정의만 변경하면 됩니다.

== 143

**Procedure abstraction**의 다섯 번째 장점은 _계산이 수행되는 방법을 쉽게 개선할 수 있다_ 는 것입니다. 예를 들어, *movieRating* 메소드가 스크립트, 연기 및 감독 등급을 두 번 더하기 때문에 쓸데없이 낭비된다고 판단핳 수 있습니다. 따라서 한 번만 계산하도록 값을 변수에 할당할 수 있습니다.

[source, java]
----
public class Movie {
// Define movieRating:
  public static int movieRating (int s, int a, int d) {
    int result = s + a + d;
    System.out.print("The rating of the movie is " + result);
    return result;
	}
}
----

다시 말하지만 *movieRating* 메소드를 통해 등급이 계산되는 모든 위치를 찾을 필요가 없으며, *movieRating* 메소드의 정의만 변경하면 됩니다.

== 144

**Procedure abstraction**의 여섯 번째 장점은 _계산 방법을 쉽게 변경할 수 있다는 것_ 입니다. 등급을 곱하기로 결정했다면 **movieRating**을 쉽게 재정의 할 수 있습니다.

[source, java]
----
public class Movie {
  // Define movieRating:
  public static int movieRating (int s, int a, int d) {
    int result = s * a * d;
    System.out.print("The rating of the movie is " + result);
    return result;
  }
}
----

== 145 연습 문제

섭씨 온도를 화씨 온도로 변환하는 **convert**라는 이름의 메소드를 작성하여 정수 인수 값을 두 배로 늘이고 30을 더하는 방식으로 변환합니다.

다음으로, 메소드가 호출될 때 마다 결과를 표시하도록 메소드를 조정합니다.

다음으로, 온도 변환을 한 번만 수행하도록 메소드를 수정하십시오.

마지막으로, 인수에 40을 추가하고 9/5를 곱한 다염 40을 빼는 방식으로 메소드를 개선합니다.

각 변경 사항에 대해 abstraction에서 제공하는 대응되는 이점에 대해 설명하십시오.

== 146: 정리

* **Procedure abstraction**는 계산 세부 정보를 메소드 내뷰로 해당 세부 정보를 abstraction barrier 뒤로 이동합니다.
* 다음과 같은 이점을 활용하기 위해 procedure abstraction를 연습해야 합니다.
** 프로그램 재사용이 쉬워진다.
** 프로그램을 이해하기 쉬워진다.
** 프로그램 디버깅이 쉬워진다.
** 프로그램이 쉽게 확장될 수 있다.
** 프로그램을 쉽게 개선할 수 있다.
** 프로그램을 쉽게 적응시킬 수 있다.
