# Chapter 2: 간단한 프로그램의 컴파일과 실행

## 23

이 단원에서는 영화의 대본, 연기, 감독에 대해 제공된 등급에서 영화의 전체 등급을 계산하는 간단한 프로그램을 컴파일하고 실행합니다. 표준 용어들 또한 검토합니다.

## 24

Java로 프로그래밍 할 때, 특정 업체가 만든 개발 환경 또는 일반적인 용도로 만들어진 에디터로 코드를 작성하고, 작성한 코드를 Java Virtual Machine이 실행할 수 있는 형식으로 변환하는 Compiler를 사용하여 프로그램을 만들 수 있습니다.

특정 업체가 만든 개발 환경을 사용하여 Java를 배우려고 하면 Java 프로그래밍 언어와는 관계없는 각 업체의 특정 개발환경을 배워야 합니다. 이 강의에서는 범용 에디터와 Compiler를 사용합니다.

## 25

일반적인 형식에서, 프로그램은 텍스트 형식으로 작성된 Source Code입니다. Source Code가 컴파일되면 Byte Code가 됩니다. Java Virtual Machine은 컴파일된 Byte Code를 실행합니다. Byte Code가 실행된다는 것은 프로그램이 실행되는 것을 의미합니다.

## 26

작성한 프로그램에서 버그(Bug)를 찾을 때, 일반적으로 다음 두 단계를 반복합니다.

```mermaid
flowchart TD
    node1[Source Code 작성 또는 수정]
    node2[Source Code 컴파일]
    node3[프로그램 실행]

    node1 --> node2
    node2 --> node3
    node2 -->|컴파일 오류 수정| node1
    node3 -->|런타임 오류 수정| node1
```

## 27

모든 Java 프로그램은 하나 이상의 클래스 정의(Class definition)을 포함하며, 각각의 클래스는 다양한 메소드 정의(method definition)을 포함합니다.

특히, 모든 독립 실행형 Java 애플리케이션은 main이라는 메소드를 정의하는 클래스를 포함해야 합니다. Java 프로그램을 실행하면 Java Virtual Machine은 main 메소드에 지정된 동작들을 수행합니다. 그렇게 해서 프로그램이 실행됩니다.

## 28: Sidetrip

Applet은 웹 브라우저에서 실행되고, 독립 실행형 프로그램이 아니므로 main 메소드를 포함하지 않습니다. 웹 브라우저가 Applet을 실행하는 메커니즘은 독립 실행형 애플리케이션과 다릅니다.

## 29: Sidetrip

Java의 메소드는 다른 프로그래밍 언어에서 말하는 function(함수) 또는 procedure(프로시저)를 대체할 수 있습니다. 메소드는 function과 procedure와 매우 비슷하나, 반드시 클래스내에 선언되어야 합니다.

## 30

각본, 연기, 연출에 대한 개별 등급을 지정하는 정수가 주어지고, 이 정수의 합이 영화의 전체 등급을 계산한다고 합시다. 지금은 각 평점이 전체 평점에 대해 같은 비율을 가진다고 가정합니다.Java에서, 프로그램에 아래와 같은 간단한 합산 식을 사용할 수 있습니다.

```java
6 + 9 + 8
```

## 31

산술식(Arithmetic Expression)이 계산되도록 하기 위해, main 메소드를 클래스내에 정의합니다.

[source, java]
----
public static void main(String [] args) {
    6 + 9 + 8;
}
----