= Chapter 9: 클래스 인스턴스 생성

특정 영화의 특성을 기억하기 위해서는 각본, 연기, 연출의 질과 관련된 것을 자연스럽게 생각할 수 있습니다. 특정 교향곡의 특징을 기술하기 위해서는 음악의 질, 연주자의 연주, 지휘의 질과 관련된 것을 자연스럽게 생각할 수 있습니다.

숫자를 사용하여 질을 표현하면, 특정 영화나 교향곡을 나타내는 숫자는 각각 영화 카테고리에 속하는 개별 자체마다 세 개의 숫자 묶음 또는 교향곡 카테고리에 속하는 각 개별 개체마다 세 개의 숫자 묶음으로 구성됩니다.

이 장에서는 Java의 큰 가치 중 하나인 Java가 실제 세계의 객체와 카테고리를 반영하는 기술적인 데이터 항목 묶음을 설명, 구성 및 조작할 수 있는 수단을 제공한다는 것을 배우게 됩니다. 이러한 특별한 매커니즘은 객체지향 프로그래밍을 전통적인 프로그래밍과 구별짓는 것입니다.

== 164

클래스를 정의한 후에는 해당 클래스에 속하는 **클래스 인스턴스**를 생성할 수 있으며, 각 인스턴스는 해당 카테고리에 속하는 개별 개체에 해당합니다.

예를 들어, **Movie** 클래스를 정의하면 모든 영화가 각본, 연기, 연출의 수준을 나타내는 숫자와 관련이 있다는 것을 나타냅니다. 그런 다음, 각본, 연기, 연출에 대한 특정 숫자를 가진 영화 인스턴스를 구성할 수 있습니다. 따라서 클래스를 사용하면 자연적으로 발생하는 객체를 설명하는 정보 묶음을 생성할 수 있습니다. 클래스는 클래스 인스터늣 생산 공작으로 작용합니다.

[source]
----
                 Instances
                   |
                   v
*---------*      ----------------------------------------------
|         |      *----*  *----*  *----*  *----*  *----*  *----*
| A Class | ---> |    |  |    |  |    |  |    |  |    |  |    |
|         |      *----*  *----*  *----*  *----*  *----*  *----*
*---------*
----

== 165

특정 클래스 인스턴스에 나타나는 변수는 **인스턴스 변수**라고 하며, **클래스 변수**와 구별됩니다. 클래스에 속하는 클래스 인스턴스의 개수만큼 인스턴스 변수 집합이 있으며, 전체 클래스에 대해 하나의 클래스 변수 집합만 있습니다.

따라서 다음 다이어그램에서 **Movie** 클래스 정의는 인스턴스 변수에 대한 설명을 포함하며, 특정 **Movie** 인스턴스의 설명은 인스턴스 변수 값이 포함됩니다.

[source]
----
*-----------------------------------------------*
| Description of instance variables,            |  <-- Definition of
|   for example, script, acting, and direction  |      the movie class
*-----------------------------------------------*

*-------------*  *-------------*  *-------------*
| script 8    |  | script 8    |  | script 6    |  <-- Particular
| acting 9    |  | acting   4  |  | acting   9  |      movie instances
| direction 6 |  | direction 6 |  | direction 5 |
*-------------*  *-------------*  *-------------*
----

== 166

인스턴스 변수의 도입으로 클래스 정의에 나타날 수 있는 세 가지 요소를 알게 되었습니다.

[source]
----
A class definition
*--------------------*
|                    |
| Class methods      |
|                    |
| Class variables    |
|                    |
| Instance variables |
|                    |
| .                  |
| .                  |
| .                  |
|                    |
*--------------------*
----

== 167

이 책에서는 종종 **Movie** 인스턴스를 movie라고 지칭합니다. 일반적으로, 클래스의 이름으로 클래스 인스턴스를 모두 소문자로 설정하여 클래스 인스턴스를 참조할 수 있습니다. 문맥이 정확하면 됩니다.

== 168

모든 클래스와 클래스 인스턴스는 **Object** 클래스의 인스턴스인 것으로 말합니다. 253 항목에서 **Object** 클래스에 대해 배오게 됩니다. 그러나 일반적으로 _object_ 라는 단어에서 볼 때, 클래스보다는 클래스 인스턴스를 나타냅니다. 문맥에 따라 예외가 있습니다.

이 책의 나머지 부분에서는 _object_ 라는 단어의 모호성을 피하기 위해 _class_ 와 _class_ _instance_ (또는 간결하게 _instance_ )라는 단어를 사용하여 클래스와 클래스 인스턴스를 참조합니다. 우리는 **Object** 클래스의 인스턴스를 나타내기 위해 _object_ 라는 단어를 예약합니다.

== 169

다음은 인스턴스 변수가 선언된 **Movie** 클래스의 Java 정의입니다. 분명히 영화를 설명하는 메모리 뭉치는 각본, 연기, 연출에 대한 세 개의 정수 값을 보유합니다.

[source, java]
----
public class Movie {
  // 먼저 인스턴스 변수 정의:
  public int script;
  public int acting;
  public int direction;
  // 클래스 정의의 나머지 부분
}
----

이 정의는 **static** 키워드가 없으므로 클래스 변수가 아닌 인스턴스 변수임을 나타냅니다.

또한 **Movie** 클래스의 정의는 **public** 키워드를 통해 **Movie** 인스턴스를 설명하는 모든 인스턴스 변수가 프로그램의 어디에서나 사용 가능하고 변경 가능하다는 것을 나타냅니다. Chapter 15에서 다른 종류의 인스턴스 변수를 배울 수 있습니다.

== 170

156 항목에서는 **선언(declaration)**이 컴파일러에 정보를 제공하는 프로그램 요소인 것을 언급했습니다. 반면 **정의(definition)**는 컴파일러가 저장소를 할당하도록 유도합니다. 인스턴스 변수만이 나타내는 클래스 정의는 저장소가 할당되는 경우에만 이루어집니다. 따라서,